### ISSUE TITLE
Extended mode keyboard is lost when history is toggled

### ISSUE THREAD

**Issue by alierdogan7** [canbax/hasap#8]
Assalamu alaykum,
When I toggle the calculation history, my calculator keyboard is switched to the basic calculator layout even though the extended keyboard mode is selected in the navbar. Example screenshot is below:

 
![image](https://user-images.githubusercontent.com/10226678/120275848-9685f880-c2ba-11eb-88ad-ac33bf9f636d.png)

**Comment by canbax** [comment]
please reopen if not fixed.
